version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rustcrypto:
        patterns:
          - "digest"
          - "hmac"
          - "md-5"
          - "sha1"
          - "sha2"
          - "aes"
          - "des"
          - "cbc"
          - "cfb-mode"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
